name: "python-test"
description: "Python testing workflow"

inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.13"

runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #  Set-up python
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    #----------------------------------------------
    # Install poetry
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv

    #----------------------------------------------
    # Install project
    #----------------------------------------------
    - name: Install project
      shell: bash
      run: poetry install --no-interaction

    #----------------------------------------------
    # Run tests
    - name: Test with pytest
      shell: bash
      run: poetry run pytest tests
